server:
  port: 9999

spring:
  application:
    name: compute-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://springcloud-eureka:8888/eureka/
    region: test1
  instance:
      prefer-ip-address: true