server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://springcloud-eureka:${server.port}/eureka/
  instance:
    preferIpAddress: true